import Head from "next/head";
import styles from "../styles/Home.module.css";
import Dock from "../components/Dock";
import TopNav from "../components/TopNav";
import Window from "../components/Window";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNav />
      <main className={styles.main}>
        <Window />
        <Dock />
      </main>
    </div>
  );
}
